In [10]:
from google.colab import drive
drive.mount('/content/drive',  force_remount=True)

Mounted at /content/drive


In [2]:
def encode_nlp_features(df, name, i):
    mlb = MultiLabelBinarizer()
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("ne")), columns=mlb.classes_, index=df.index).add_prefix('ne_'))], axis=1)
    #print(df.shape)
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("iob")), columns=mlb.classes_, index=df.index).add_prefix('iob_'))], axis=1)
    #print(df.shape)
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("alpha")), columns=mlb.classes_, index=df.index).add_prefix('al_'))], axis=1)
    #print(df.shape)
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("digit")), columns=mlb.classes_, index=df.index).add_prefix('dig_'))], axis=1)
    #print(df.shape)
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("punc")), columns=mlb.classes_, index=df.index).add_prefix('punc_'))], axis=1)
    #print(df.shape)
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("url")), columns=mlb.classes_, index=df.index).add_prefix('url_'))], axis=1)
    #print(df.shape)
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("oov")), columns=mlb.classes_, index=df.index).add_prefix('oov_'))], axis=1)
    #print(df.shape)
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("stop")), columns=mlb.classes_, index=df.index).add_prefix('stop_'))], axis=1)
    #print(df.shape)
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("coarsepos")), columns=mlb.classes_, index=df.index).add_prefix('cpos_'))], axis=1)
    #print(df.shape)
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("finepos")), columns=mlb.classes_, index=df.index).add_prefix('fpos_'))], axis=1)
    #print(df.shape)
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("dep")), columns=mlb.classes_, index=df.index).add_prefix('dep_'))], axis=1)
    #print(df.shape)
    df = pd.concat([df,(pd.DataFrame(mlb.fit_transform(df.pop("offset")), columns=mlb.classes_, index=df.index).add_prefix('off_'))], axis=1)
    #print(df.shape)
    #print(df.columns.values.tolist())
    df.to_pickle('output\\nlp-bilstm-attn\\df_' + name + '_nlp_features_' + str(i) + '.pkl')
    return df

In [12]:
"""
This method should generate all the natural language processing features
"""
def generate_nlp_features(df, i, name=""):
    sentence_ne = []
    sentence_iob = []
    sentence_alpha = []
    sentence_isdigit = []
    sentence_ispunc = []
    sentence_isurl = []
    sentence_isoov = []
    sentence_isstop = []
    sentence_coarsepos = []
    sentence_finepos = []
    sentence_dep = []
    sentence_offset = []

    i=0
   
    """NEED TO CHANGE THE FUNCTIONAL COLUMN"""
    for entries in df['Previous_User_Utterance']: #each entry is a sentence
        if i%100==0:
            print(i)
        i=i+1

        doc = nlp(entries) #Spacy function to get tags
        #print(doc)

        ne = []
        iob = []
        alpha = []
        isdigit = []
        ispunc = []
        isurl = []
        isoov = []
        isstop = []
        coarsepos = []
        finepos = []
        dep = []
        offset = []

        """
        For words in the sentence
        """
        for token in doc:
            """
            Named Entity Type
            """
            #print("NE Type:", token.ent_type)
            ne.append(token.ent_type_)

            """
            IOB code of named entity tag. B means the token begins an entity, 
            I means it is inside an entity, O means it is outside an entity, and 
            '' means no entity tag is set.
            """
            #print("IOB:", token.ent_iob) 
            iob.append(token.ent_iob_)

            """
            Does the token contain alphabetic characters?
            """
            #print("Alpha:", token.is_alpha)
            alpha.append(str(token.is_alpha))

            """
            Does the token contain digits?
            """
            #print("Digits:", token.is_digit)
            isdigit.append(str(token.is_digit))

            """
            Is the token punctuation?
            """
            #print("Punc:", token.is_punct)
            ispunc.append(str(token.is_punct))

            """
            Is the token like urls?
            """
            #print("Url:", token.like_url)
            isurl.append(str(token.like_url))

            """
            Is the token out-of-vocabulary?
            """
            #print("OOV:", token.is_oov)
            isoov.append(str(token.is_oov))

            """
            Is the token a stopword?
            """
            #print("Stop:", token.is_stop)
            isstop.append(str(token.is_stop))

            """
            Coarse-grained POS
            """
            #print("Coarse POS:", token.pos_)
            coarsepos.append(token.pos_)

            """
            Fine-grained POS
            """
            #print("Fine POS:", token.tag_)
            finepos.append(token.tag_)

            """
            Syntactic Dependency Relation
            """
            #print("Dependency:", token.dep_)
            dep.append(token.dep_)

            """
            Character offset
            """
            #print("Offset:", token.idx)
            coff = token.idx
            if(coff<100):
                off = 1
            elif(coff<200): 
                off =2
            elif(coff<300): 
                off =3
            elif(coff<400): 
                off =4
            elif(coff<500): 
                off =5
            elif(coff<600): 
                off =6
            elif(coff<700): 
                off =7
            elif(coff<800): 
                off =8
            elif(coff<900): 
                off =9
            elif(coff<1000): 
                off =10
            else: 
                off =11
            offset.append(off)
            
            #print(type(token.is_alpha))
            #break

        sentence_ne.append(ne)
        sentence_iob.append(iob)
        sentence_alpha.append(alpha)
        sentence_isdigit.append(isdigit)
        sentence_ispunc.append(ispunc)
        sentence_isurl.append(isurl)
        sentence_isoov.append(isoov)
        sentence_isstop.append(isstop)
        sentence_coarsepos.append(coarsepos)
        sentence_finepos.append(finepos)
        sentence_dep.append(dep)
        sentence_offset.append(offset)
    df["ne"] = sentence_ne
    df["iob"] = sentence_iob
    df["alpha"] = sentence_alpha
    df["digit"] = sentence_isdigit
    df["punc"] = sentence_ispunc
    df["url"] = sentence_isurl
    df["oov"] = sentence_isoov
    df["stop"] = sentence_isstop
    df["coarsepos"] = sentence_coarsepos
    df["finepos"] = sentence_finepos
    df["dep"] = sentence_dep
    df["offset"] = sentence_offset
    
    print(len(sentence_ne) == len(sentence_iob) == len(sentence_alpha) == len(sentence_isdigit) == \
          len(sentence_ispunc) == len(sentence_isurl) == len(sentence_isoov) == len(sentence_isstop) \
          == len(sentence_coarsepos) == len(sentence_finepos) == len(sentence_dep) == len(sentence_offset))

    df.to_pickle('output\\nlp-bilstm-attn\\df_' + name + '_nlp_features_intermediate_' + str(i) + '.pkl')
    return df

In [5]:
def get_nlp_encodings(i):
    """
    Obtain the dataset
    """
    print("Inside get_nlp_encodings")
    # Extracted the text for nlp embeddings  
    df_X_train= pd.read_pickle('/content/drive/My Drive/Python Notebook/SCS_CONVEX/data-files/search/X_train_' + str(i) + '.pkl')
    df_X_test= pd.read_pickle('/content/drive/My Drive/Python Notebook/SCS_CONVEX/data-files/search/X_test_' + str(i) + '.pkl')
    df_Y_train=pd.read_pickle('/content/drive/My Drive/Python Notebook/SCS_CONVEX/data-files/search/Y_train_' + str(i) + '.pkl')
    df_Y_test=pd.read_pickle('/content/drive/My Drive/Python Notebook/SCS_CONVEX/data-files/search/Y_test_' + str(i) + '.pkl')
    #print(df_X_train.shape) #(835, 5)
    #print(df_Y_train.shape) #(835, 1)
    #print(df_X_test.shape) #(209, 5)
    #print(df_Y_test.shape) #(209, 1)
    
    """
    merging the output labels to predictors
    """
    df_train = pd.concat([df_X_train,df_Y_train], axis=1)
    df_test = pd.concat([df_X_test,df_Y_test], axis=1)
    print("The size of training and test sets:", df_train.shape, df_test.shape)
    r,c = df_train.shape
    #print("Rows in training data =", r)
    """
    merging training and test data to one dataframe
    """
    df = pd.concat([df_train,df_test])
    #print("Final df:", df.shape)
    #print(df.head(2))
    """
    generating the nlp features using spacy
    """
    df_nlp = generate_nlp_features(df, i, 'all')
    #print("After-spacy:", df_nlp.shape, df_nlp.columns.values)
    #print(df_nlp.head(2))
    
    """
    encoding the nlp features using multilabelbinarizer
    """
    df_nlp_enc = encode_nlp_features(df_nlp, 'all_nlp_enc', i)
    #print(df_nlp_enc.shape)
    #print(df_nlp_enc.head(2))
    #print(df_nlp_enc.shape, df_nlp_enc.columns.values.tolist())
    df_nlp_enc.drop(['Utterance_Number', 'Duration', 'Speaker', 'System_Number', 'Search_Task', 'Previous_User_Utterance', 'Previous_User_Speech_Act', 'Previous_Speech_Act', 'Previous_Search_Act','Search_acts'], axis=1, inplace=True)
                     #['Transcript', 'Query_counter', 'Length', 'If_Intermediary', 'Complexity', 'Speech_acts'], axis=1, inplace=True)
    #print(df_nlp_enc.shape, df_nlp_enc.columns.values.tolist())
    train_split = df_nlp_enc.iloc[:r,:]
    test_split = df_nlp_enc.iloc[r:,:]
    print("Size after split:",train_split.shape, test_split.shape, df_Y_train.shape, df_Y_test.shape)
    return train_split, test_split, df_Y_train, df_Y_test

In [14]:
from keras.engine.topology import Layer
class AttentionLayer(Layer):
   
    def __init__(self,attention_dim=100,return_coefficients=False,**kwargs):
        # Initializer 
        self.supports_masking = True
        self.return_coefficients = return_coefficients
        self.init = initializers.get('glorot_uniform') # initializes values with uniform distribution
        self.attention_dim = attention_dim
        super(AttentionLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        # Builds all weights
        # W = Weight matrix, b = bias vector, u = context vector
        assert len(input_shape) == 3
        self.W = K.variable(self.init((input_shape[-1], self.attention_dim)),name='W')
        self.b = K.variable(self.init((self.attention_dim, )),name='b')
        self.u = K.variable(self.init((self.attention_dim, 1)),name='u')
        self.trainable_weight = [self.W, self.b, self.u]

        super(AttentionLayer, self).build(input_shape)

    def compute_mask(self, input, input_mask=None):
        return None

    def call(self, hit, mask=None):
        # Here, the actual calculation is done
        uit = K.bias_add(K.dot(hit, self.W),self.b)
        uit = K.tanh(uit)
        
        ait = K.dot(uit, self.u)
        ait = K.squeeze(ait, -1)
        ait = K.exp(ait)
        
        if mask is not None:
            ait *= K.cast(mask, K.floatx())

        ait /= K.cast(K.sum(ait, axis=1, keepdims=True) + K.epsilon(), K.floatx())
        ait = K.expand_dims(ait)
        weighted_input = hit * ait
        
        if self.return_coefficients:
            return [K.sum(weighted_input, axis=1), ait]
        else:
            return K.sum(weighted_input, axis=1)

    def compute_output_shape(self, input_shape):
        if self.return_coefficients:
            return [(input_shape[0], input_shape[-1]), (input_shape[0], input_shape[-1], 1)]
        else:
            return input_shape[0], input_shape[-1]

In [7]:
"""
Creating Bi-LSTM model using word embeddings
"""

def create_bilstm_model_nlp(reshaped_data):
    samples,timesteps,features = reshaped_data.shape
    input_data = Input(shape=(timesteps,features))
    # lstm needs (samples,timesteps,features) tensor as the input
    x = Bidirectional(LSTM(BATCH_SIZE, return_sequences=True, dropout=0.25, recurrent_dropout=0.1))(input_data) 
    #x = Bidirectional(LSTM(BATCH_SIZE, return_sequences=True, dropout=0.25))(input_data) 
    x, sent_coeffs = AttentionLayer(features,return_coefficients=True,name='sent_attention')(x)
    #x = GlobalMaxPool1D()(x)
    #x = Dense(100, activation="relu", kernel_regularizer=regularizers.l2(0.000001), activity_regularizer=regularizers.l1(0.0005))(x)
    #x = Dense(100, activation="relu")(x)
    x = Dropout(0.25)(x)
    x = Dense(4, activation="softmax")(x) #output layer
    model = Model(inputs=input_data, outputs=x)
    return model  

In [8]:
def execute_bilstm_nlp(i):
    df_train_nlp_encodings, df_test_nlp_encodings, df_Y_train, df_Y_test = get_nlp_encodings(i)
    train_nlp_enc = df_train_nlp_encodings.values
    test_nlp_enc = df_test_nlp_encodings.values
    print(train_nlp_enc)
    print(train_nlp_enc.shape, test_nlp_enc.shape)   
    
    timestamp = 1 #number of successive sequences combined
    
    r, c = df_train_nlp_encodings.shape
    staggering = r - timestamp + 1 # final number of instances generated 
    X_train_reshaped = np.concatenate([train_nlp_enc[x:x+timestamp,:] for x in range(r-timestamp+1)])
    X_train_reshaped = X_train_reshaped.reshape(staggering, timestamp, c) # c is the number of features
    #print(X_train_reshaped)
    print(X_train_reshaped.shape)
    
    r2, c2 = df_test_nlp_encodings.shape
    staggering2 = r2 - timestamp + 1 # final number of instances generated 
    X_test_reshaped = np.concatenate([test_nlp_enc[x:x+timestamp,:] for x in range(r2-timestamp+1)])
    X_test_reshaped = X_test_reshaped.reshape(staggering2, timestamp, c2) # c2 is the number of features
    #print(X_test_reshaped)
    print(X_test_reshaped.shape)
    
    df_Y_train = df_Y_train.iloc[timestamp-1:,]
    df_Y_test = df_Y_test.iloc[timestamp-1:,]
    
    model = create_bilstm_model_nlp(X_train_reshaped)
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['binary_accuracy', 'categorical_accuracy'])
    model.summary()
    
    """
    encoding the output labels
    """
    encoder = LabelEncoder()
    encoder.fit(df_Y_train)
    training_op_labels_encoded = encoder.transform(df_Y_train)
    test_op_labels_encoded = encoder.transform(df_Y_test)
    print(training_op_labels_encoded.shape, test_op_labels_encoded.shape)
    """
    converting the output labels to one-hot form
    """
    training_op_labels_onehot= np_utils.to_categorical(training_op_labels_encoded)
    test_op_labels_onehot = np_utils.to_categorical(test_op_labels_encoded)

    #print(training_op_labels_onehot)
    print(training_op_labels_onehot.shape, len(training_op_labels_onehot))
    print(test_op_labels_onehot.shape, len(test_op_labels_onehot))

    print("X_train_reshaped", X_train_reshaped.shape)
    print("training_op_labels_onehot", training_op_labels_onehot.shape)
    model.fit(X_train_reshaped, training_op_labels_onehot, batch_size=BATCH_SIZE, epochs=EPOCHS, validation_split=0.1)

    
    """
    evaluate model
    """
    print(model.metrics_names)
    loss, binary_accuracy, categorical_accuracy = model.evaluate(X_test_reshaped, y = test_op_labels_onehot, batch_size=BATCH_SIZE, verbose=1)
    
    print(loss, binary_accuracy, categorical_accuracy)

    """
    predict the probabilty of output classes
    and pick the best one
    """
    prediction_vector = model.predict(X_test_reshaped, batch_size=BATCH_SIZE, verbose=1)
    predicted_classes = np.argmax(prediction_vector, axis=1)
    original_classes = np.argmax(test_op_labels_onehot, axis=1)
    
    """
    # verification of correctness:
    total_correct = sum(original_classes == predicted_classes)
    print("Total number of correct predictions:",total_correct)
    print("Accuracy:",total_correct/len(test_op_labels_onehot))
    acc = np.sum(conf_mat.diagonal()) / np.sum(conf_mat)
    print('Overall accuracy: {} %'.format(acc*100))
    """
    conf_mat = confusion_matrix(predicted_classes, original_classes)
    print(conf_mat)

    """
    # show the inputs and predicted outputs
    list_bilstm_prediction = []
    for i in range(len(X_test_reshaped)):
        row = []
        row.extend(X_test_reshaped[i])
        row.extend(test_op_labels_onehot[i])
        list_bilstm_prediction.append(row)
    df_bilstm_prediction = pd.DataFrame(data=list_bilstm_prediction)
    df_bilstm_prediction.to_pickle("nlp_bilstm_predictions.pkl")
    """
    
    return predicted_classes, categorical_accuracy, binary_accuracy, conf_mat

In [15]:
"""
import tensorflow as tf
tf_config = tf.compat.v1.ConfigProto()
tf_config.gpu_options.allow_growth = True
tf_config.gpu_options.per_process_gpu_memory_fraction = 0.9
tf_config.allow_soft_placement = True
#physical_devices = tf.config.experimental.list_physical_devices('GPU')
try:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
except:
    # Invalid device or cannot modify virtual devices once initialized.
    pass
"""


import pandas as pd
import numpy as np 
from numpy import array

from sklearn.preprocessing import MultiLabelBinarizer, LabelEncoder
from sklearn.metrics import confusion_matrix

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation, Bidirectional, GlobalMaxPool1D, GRU, TimeDistributed
from keras.layers.merge import concatenate
from keras.models import Model, model_from_json
from keras import initializers, regularizers, constraints, optimizers, layers
from keras.utils import np_utils, to_categorical
from keras.engine.topology import Layer
from keras import backend as K

# checkpoint
from keras.callbacks import ModelCheckpoint

from tensorflow.keras.layers import Attention

"""
Required for NLP model
"""
import spacy
import en_core_web_sm
nlp = en_core_web_sm.load()   


BATCH_SIZE=32
EPOCHS=1 #300

file = open('/content/drive/My Drive/Python Notebook/SCS_CONVEX/output/Search Tasks/nlp-attn/bilstm_nlp_op.txt','w') #overwrites previous
file.close()

if __name__== "__main__":
    df_prediction = pd.DataFrame()
    df_accuracy =  pd.DataFrame()
    file = open('/content/drive/My Drive/Python Notebook/SCS_CONVEX/output/Search Tasks/nlp-attn/bilstm_nlp_op.txt','a') #append mode 
    for i in range(1,3):
        outputname = 'nlp_'+ str(i)        
        predictions, acc_cat, acc_bin, conf_matrix = execute_bilstm_nlp(i)
        df_prediction[outputname] = predictions
        df_accuracy[i] = [acc_cat]
        file.write("\nIteration:" + str(i) + "\nCategorical Accuracy:" + str(acc_cat) + 
                   "\nBinary Accuracy:" + str(acc_bin) + "\nConfusion Matrix:\n" + str(conf_matrix) + "\n\n")
    df_prediction.to_csv('/content/drive/My Drive/Python Notebook/SCS_CONVEX/output/Search Tasks/nlp-attn/predictions_bilstm_nlp.csv')    
    df_accuracy.to_csv('/content/drive/My Drive/Python Notebook/SCS_CONVEX/output/Search Tasks/nlp-attn/accuracy_bilstm_nlp.csv')    
    file.close()

Inside get_nlp_encodings
The size of training and test sets: (406, 10) (102, 10)
0
100
200
300
400
500
True
Size after split: (406, 123) (102, 123) (406, 1) (102, 1)
[[1 0 0 ... 1 1 0]
 [1 0 0 ... 1 1 0]
 [1 0 0 ... 1 0 0]
 ...
 [1 0 0 ... 1 0 0]
 [1 0 0 ... 1 0 0]
 [1 0 0 ... 1 0 0]]
(406, 123) (102, 123)
(406, 1, 123)
(102, 1, 123)
Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 1, 123)]          0         
_________________________________________________________________
bidirectional_1 (Bidirection (None, 1, 64)             39936     
_________________________________________________________________
sent_attention (AttentionLay [(None, 64), (None, 1, 1) 8118      
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
________________________________________________

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


12/12 [==============================] - 1s 69ms/step - loss: 1.3714 - binary_accuracy: 0.7500 - categorical_accuracy: 0.2767 - val_loss: 1.2497 - val_binary_accuracy: 0.7500 - val_categorical_accuracy: 0.4634
['loss', 'binary_accuracy', 'categorical_accuracy']
4/4 [==============================] - 0s 4ms/step - loss: 1.3501 - binary_accuracy: 0.7500 - categorical_accuracy: 0.2745
1.350101351737976 0.75 0.27450981736183167
4/4 [==============================] - 0s 3ms/step
[[ 4  2  2  2]
 [ 0  0  0  0]
 [33 27 24  8]
 [ 0  0  0  0]]
Inside get_nlp_encodings
The size of training and test sets: (406, 10) (102, 10)
0
100
200
300
400
500
True
Size after split: (406, 123) (102, 123) (406, 1) (102, 1)
[[1 0 0 ... 1 0 0]
 [1 0 0 ... 1 0 0]
 [1 0 0 ... 1 0 0]
 ...
 [1 0 0 ... 1 0 0]
 [1 0 0 ... 1 0 0]
 [1 0 0 ... 1 0 0]]
(406, 123) (102, 123)
(406, 1, 123)
(102, 1, 123)
Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output 

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


12/12 [==============================] - 1s 67ms/step - loss: 1.3213 - binary_accuracy: 0.7500 - categorical_accuracy: 0.3233 - val_loss: 1.3488 - val_binary_accuracy: 0.7500 - val_categorical_accuracy: 0.3415
['loss', 'binary_accuracy', 'categorical_accuracy']
4/4 [==============================] - 0s 4ms/step - loss: 1.2661 - binary_accuracy: 0.7500 - categorical_accuracy: 0.3922
1.2660704851150513 0.75 0.3921568691730499
4/4 [==============================] - 0s 3ms/step
[[18 14 22  6]
 [ 0  0  0  0]
 [14  5 22  1]
 [ 0  0  0  0]]
